"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";

const groups=[
 {label:"WORKSPACE",items:[["/dashboard","Overview","grid","nav.overview"],["/hot-leads","Hot Leads","users","nav.hot_leads"],["/leads","Leads","user","nav.leads"],["/customers","Customers","user","nav.customers"],["/calls","Calls","phone","nav.calls"],["/appointments","Appointments","calendar","nav.appointments"],["/jobs","Jobs","briefcase","nav.jobs"]]},
 {label:"OPERATIONS",items:[["/follow-ups","Follow-ups","calendar","nav.followups"],["/conversations","Conversations","message","nav.conversations"],["/resolved","Resolved","check","nav.resolved"],["/trash","Trash","trash","nav.trash"]]},
 {label:"MANAGE",items:[["/team","Team & Roles","users","nav.team"],["/settings","Settings","settings","nav.settings"],["/support","Support","help","nav.support"]]}
];

export default function Sidebar({collapsed,onToggle}){
 const pathname=usePathname();
 const [keys,setKeys]=useState(null);
 useEffect(()=>{let live=true;fetch('/api/navigation-permissions',{cache:'no-store'}).then(async r=>({ok:r.ok,j:await r.json()})).then(({ok,j})=>{if(live)setKeys(new Set(ok?(j.permissionKeys||[]):[]));}).catch(()=>live&&setKeys(new Set()));return()=>{live=false};},[]);
 const can=useMemo(()=>{if(keys===null||keys.has('*'))return()=>true;return k=>keys.has(k);},[keys]);
 return <aside className={`ph-old-sidebar ${collapsed?'collapsed':''}`}>
  <div className="ph-old-brand"><div className="ph-old-logo">P</div><div className="ph-old-brand-copy"><strong>PHONIQ</strong><small>SERVICE CRM</small></div></div>
  <div className="ph-old-scroll">{groups.map(g=>{const items=g.items.filter(i=>can(i[3]));if(!items.length)return null;return <nav key={g.label} className="ph-old-group"><div className="ph-old-group-title">{g.label}</div>{items.map(([href,label,icon])=>{const active=pathname===href||(href!='/dashboard'&&pathname?.startsWith(href+'/'));return <Link key={href} href={href} className={`ph-old-link ${active?'active':''}`} title={collapsed?label:undefined}><span className="ph-old-icon"><Icon name={icon}/></span><span className="ph-old-text">{label}</span></Link>})}</nav>})}</div>
  <button className="ph-old-collapse" onClick={onToggle} aria-label={collapsed?'Expand menu':'Collapse menu'}><svg viewBox="0 0 24 24"><path d={collapsed?'m9 6 6 6-6 6':'m15 6-6 6 6 6'}/></svg><span>{collapsed?'':'Collapse menu'}</span></button>
  <style jsx global>{`
   .ph-old-sidebar{width:276px;min-width:276px;height:100vh;position:sticky;top:0;z-index:80;display:flex;flex-direction:column;background:#fff;border-right:1px solid #e6ebf2;overflow:hidden;transition:width .22s cubic-bezier(.4,0,.2,1),min-width .22s cubic-bezier(.4,0,.2,1);font-family:var(--font-geist-sans),Arial,sans-serif}
   .ph-old-sidebar.collapsed{width:80px;min-width:80px}.ph-old-brand{height:88px;min-height:88px;display:flex;align-items:center;gap:11px;padding:18px 17px;box-sizing:border-box;border-bottom:1px solid #eef2f7}.ph-old-logo{width:42px;height:42px;flex:0 0 42px;border-radius:12px;background:#2563eb;color:#fff;display:grid;place-items:center;font-size:14px;font-weight:850;box-shadow:0 6px 15px rgba(37,99,235,.18)}
   .ph-old-brand-copy{width:150px;opacity:1;overflow:hidden;white-space:nowrap;transition:width .18s ease,opacity .12s ease}.ph-old-sidebar.collapsed .ph-old-brand-copy{width:0;opacity:0}.ph-old-brand-copy strong{display:block;color:#0f172a;font-size:16px;font-weight:800}.ph-old-brand-copy small{display:block;margin-top:4px;color:#94a3b8;font-size:9px;font-weight:750;letter-spacing:1.7px}
   .ph-old-scroll{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;padding:5px 0 8px}.ph-old-group{padding:16px 10px 0}.ph-old-group-title{height:16px;padding:0 12px 6px;color:#8da0ba;font-size:9px;font-weight:900;letter-spacing:1.7px;white-space:nowrap;overflow:hidden}.ph-old-sidebar.collapsed .ph-old-group-title{opacity:0}
   .ph-old-link{height:46px;display:flex;align-items:center;gap:9px;margin:2px 0;padding:0 10px;border-radius:11px;box-sizing:border-box;text-decoration:none;color:#465971;font-size:13.5px;font-weight:700;line-height:1;transition:background .15s ease,color .15s ease}.ph-old-link:hover{background:#f7f9fc;color:#142036}.ph-old-link.active{background:#eaf2ff;color:#1459e6}.ph-old-icon{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border-radius:9px;color:#88a3c7}.ph-old-link.active .ph-old-icon{background:#fff;color:#1459e6;box-shadow:0 3px 10px rgba(15,23,42,.06)}.ph-old-icon svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}
   .ph-old-text{width:170px;opacity:1;overflow:hidden;white-space:nowrap;transition:width .18s ease,opacity .1s ease}.ph-old-sidebar.collapsed .ph-old-text{width:0;opacity:0}.ph-old-sidebar.collapsed .ph-old-link{padding-left:13px}.ph-old-collapse{height:48px;min-height:48px;margin:8px 11px 12px;display:flex;align-items:center;justify-content:center;gap:7px;border:1px solid #dbe3ed;border-radius:10px;background:#fff;color:#52647b;font-size:11.5px;font-weight:700;cursor:pointer;overflow:hidden;white-space:nowrap}.ph-old-collapse:hover{background:#f8fafc}.ph-old-collapse svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
  `}</style>
 </aside>
}
function Icon({name}){const p={viewBox:'0 0 24 24','aria-hidden':'true'};if(name==='grid')return <svg {...p}><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>;if(name==='users')return <svg {...p}><circle cx="8" cy="8" r="3"/><path d="M2.5 19a5.5 5.5 0 0 1 11 0M16 5.5a3 3 0 0 1 0 5.8M15.5 14a5 5 0 0 1 6 5"/></svg>;if(name==='user')return <svg {...p}><circle cx="12" cy="7.5" r="3.5"/><path d="M5.5 20a6.5 6.5 0 0 1 13 0"/></svg>;if(name==='phone')return <svg {...p}><path d="M7 3H4.5A1.5 1.5 0 0 0 3 4.5C3 13.6 10.4 21 19.5 21a1.5 1.5 0 0 0 1.5-1.5V17l-4.2-1.2-1.1 2a14.2 14.2 0 0 1-9.5-9.5l2-1.1L7 3z"/></svg>;if(name==='calendar')return <svg {...p}><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>;if(name==='briefcase')return <svg {...p}><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V5h6v2M3 12h18"/></svg>;if(name==='message')return <svg {...p}><path d="M20 15a4 4 0 0 1-4 4H8l-5 2V7a4 4 0 0 1 4-4h9a4 4 0 0 1 4 4z"/></svg>;if(name==='check')return <svg {...p}><path d="m5 12 4 4L19 6"/></svg>;if(name==='trash')return <svg {...p}><path d="M4 6h16M9 6V4h6v2M18 6l-1 15H7L6 6M10 10v7M14 10v7"/></svg>;if(name==='settings')return <svg {...p}><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a8 8 0 0 0-1.8-1L14.4 3h-4.8l-.4 3.1a8 8 0 0 0-1.8 1L5 6.1 3 9.5 5 11a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1a8 8 0 0 0 1.8 1l.4 3.1h4.8l.4-3.1a8 8 0 0 0 1.8-1l2.4 1 2-3.4L19 13a7 7 0 0 0 0-1z"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="9"/><path d="M12 17h.01M9.5 9a2.5 2.5 0 1 1 4 2c-1 .7-1.5 1.2-1.5 2.5"/></svg>}
